version: '3.4'
services:
  db:
    image: 'postgres'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=chainstack
      - POSTGRES_USER=cs
      - POSTGRES_PASSWORD=abc

  server:
    depends_on:
      - db
    image: chainstack
    ports:
      - '3001:3001'
    environment:
      - DB_URL=db
    command: npm run start

  test_db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=chainstack
      - POSTGRES_USER=cs
      - POSTGRES_PASSWORD=abc
  test:
    depends_on:
      - test_server
    image: chainstack
    volumes:
      - './tests:/usr/src/app/tests'
      - './src/db/schema.sql:/usr/src/app/src/db/schema.sql'
    environment:
      - SERVER_URL=http://test_server:3001
      - DB_URL=test_db
    command: npm test

  test_server:
    depends_on:
      - test_db
    image: chainstack
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - DB_URL=test_db
    command: npm run dev
