version: '3.4'
services:
  db:
    image: 'postgres'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=chainstack
      - POSTGRES_USER=cs
      - POSTGRES_PASSWORD=abc

  server:
    depends_on:
      - db
    image: chainstack
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DB_URL=db
    command: npm run start

  test_db:
    image: 'postgres'
    environment:
      - POSTGRES_DB=chainstack
      - POSTGRES_USER=cs
      - POSTGRES_PASSWORD=abc
  test:
    depends_on:
      - test_server
    image: chainstack
    environment:
      - SERVER_URL=http://test_server:3001
      - DB_URL=test_db
    command: npm test

  test_server:
    depends_on:
      - test_db
    image: chainstack
    environment:
      - NODE_ENV=test
      - DB_URL=test_db
    command: npm run dev
